### ISSUE TITLE
Error running npm run transifex

### ISSUE THREAD

**Issue by 1ec5** [Project-OSRM/osrm-text-instructions#108]
As of #107, `npm run transifex` fails with the following error:

```
> osrm-text-instructions@0.3.0 transifex /Users/mxn/hub/osrm-text-instructions
> node scripts/transifex.js

/Users/mxn/hub/osrm-text-instructions/scripts/transifex.js:26
Object.keys(languages.codes).forEach((code) => {
       ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.<anonymous> (/Users/mxn/hub/osrm-text-instructions/scripts/transifex.js:26:8)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
```

/cc @patjouk @freenerd

**Comment by patjouk** [comment]
Good catch (and sorry about that!). I've Just committed [this patch](https://github.com/Project-OSRM/osrm-text-instructions/commit/145f4f3064ab3aaa06b9704c3a96e0e5e173051a). Can you tell me if it fixes this issue?

**Comment by 1ec5** [comment]
Perfect, thanks!
